import MetricCard from "../components/MetricCard";
import TopicRow from "../components/TopicRow";

const formatTime = (seconds) => `${Math.floor((Number(seconds) || 0) / 60)}m ${Math.round((Number(seconds) || 0) % 60)}s`;

export default function ResultsView({ result, topics, onPractice, onDashboard }) {
  if (!result) return <div className="state-panel"><h2>No result to show yet.</h2><button className="button button-dark" onClick={onPractice}>Start practice</button></div>;
  return <div className="results-layout reveal"><div className="results-heading"><div><p className="eyebrow">Session complete</p><h1>That rep is<br /><span>in the bank.</span></h1></div><div className="score-stamp"><strong>{Number(result.accuracy || 0).toFixed(0)}%</strong><span>accuracy</span></div></div><section className="metric-grid results-metrics"><MetricCard label="Score" value={`${result.correct} / ${result.total_questions}`} detail="Correct answers" accent="teal" /><MetricCard label="Attempted" value={result.attempted} detail={`${result.unanswered} unanswered`} accent="coral" /><MetricCard label="Incorrect" value={result.incorrect} detail="Review the patterns" accent="yellow" /><MetricCard label="Total time" value={formatTime(result.total_time_seconds)} detail={`${formatTime(result.average_time_per_attempted_question_seconds)} per question`} accent="ink" /></section><section className="panel results-topics"><div className="panel-heading"><div><p className="eyebrow">What to carry forward</p><h2>Topic performance</h2></div></div>{topics.length ? topics.slice(0, 6).map((topic) => <TopicRow key={topic.topic} topic={topic} tone={topic.category === "Needs Practice" ? "coral" : "teal"} />) : <p className="empty-copy">Topic detail will appear as your completed history grows.</p>}</section><div className="results-actions"><button className="button button-coral" onClick={onPractice}>Practice again ↗</button><button className="button button-outline" onClick={onDashboard}>Back to dashboard</button></div></div>;
}
